apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    component: user
  ports:
    - port: 5000
      name: http
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: gcr.io/wdmproject23-v2/user
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "--chdir", "/payment", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: payment-db
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "2"
