auth:
  password: redis
master:
  persistence:
    size: 4Gi
  resources:
    requests:
      memory: 2Gi
      cpu: 1
replica:
  replicaCount: 1
  persistence:
    size: 4Gi
  resources:
    requests:
      memory: 2i
      cpu: 1